// Command valgen 是基于 gengo + validate struct tag 的静态校验代码生成器。
//
// 用法（在目标 package 目录下执行）：
//
//	go run github.com/formal-you/validation-gen/cmd/valgen \
//	  -type=CreateUserRequest -type=Order \
//	  -output=zz_generated.validation.go
//
// 生成文件头包含 "Code generated by valgen; DO NOT EDIT."；
// 生成失败时不覆盖已有生成文件（先写临时文件再原子替换）。
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	gengoparser "k8s.io/gengo/v2/parser"

	"github.com/formal-you/validation-gen/pkg/gen"
	"github.com/formal-you/validation-gen/pkg/ir"
	"github.com/formal-you/validation-gen/pkg/parser"
)

// typeFlag 支持重复的 -type 参数。
type typeFlag []string

func (t *typeFlag) String() string {
	return strings.Join(*t, ",")
}

func (t *typeFlag) Set(v string) error {
	*t = append(*t, v)
	return nil
}

func main() {
	var typeNames typeFlag
	output := flag.String("output", "zz_generated.validation.go", "生成文件路径（相对当前目录）")
	flag.Var(&typeNames, "type", "要生成校验方法的类型名，可重复指定")
	flag.Parse()

	if len(typeNames) == 0 {
		fmt.Fprintln(os.Stderr, "错误：至少指定一个 -type")
		flag.Usage()
		os.Exit(2)
	}

	// 1. 用 gengo 加载当前目录 package 并建立类型 universe。
	p := gengoparser.New()
	if err := p.LoadPackages("."); err != nil {
		fmt.Fprintf(os.Stderr, "错误：加载当前 package 失败: %v\n", err)
		os.Exit(1)
	}
	u, err := p.NewUniverse()
	if err != nil {
		fmt.Fprintf(os.Stderr, "错误：解析类型失败: %v\n", err)
		os.Exit(1)
	}
	requested := p.UserRequestedPackages()
	if len(requested) != 1 {
		fmt.Fprintf(os.Stderr, "错误：期望加载 1 个 package，实际 %d 个: %v\n", len(requested), requested)
		os.Exit(1)
	}
	pkg := u[requested[0]]
	if pkg == nil {
		fmt.Fprintf(os.Stderr, "错误：package %q 未在 universe 中找到\n", requested[0])
		os.Exit(1)
	}

	// 2. 逐个类型解析规则 IR，解析失败即整体失败（不写输出文件）。
	var typeRules []ir.TypeRules
	for _, name := range typeNames {
		t := pkg.Types[name]
		if t == nil {
			fmt.Fprintf(os.Stderr, "错误：类型 %q 不存在于 package %q\n", name, requested[0])
			os.Exit(1)
		}
		tr, err := parser.ParseType(requested[0], t)
		if err != nil {
			fmt.Fprintf(os.Stderr, "错误：%v\n", err)
			os.Exit(1)
		}
		typeRules = append(typeRules, tr)
	}

	// 3. 生成并写入。
	src, err := gen.Generate(gen.Options{PackageName: pkg.Name, Types: typeRules})
	if err != nil {
		fmt.Fprintf(os.Stderr, "错误：%v\n", err)
		os.Exit(1)
	}
	if err := gen.WriteFile(*output, src); err != nil {
		fmt.Fprintf(os.Stderr, "错误：%v\n", err)
		os.Exit(1)
	}
	fmt.Printf("已生成 %s（类型：%s）\n", *output, strings.Join(typeNames, ", "))
}
